Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(rw_with_food_multiple_walkers.py:22721): Gdk-CRITICAL **: 15:05:16.903: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(rw_with_food_multiple_walkers.py:22721): Gdk-CRITICAL **: 15:05:16.905: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
2047.7763517820276
